---
name: Openwrt Build

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    name: Build H6 Openwrt
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: |
          echo $FORCE_UNSAFE_CONFIGURE
        env: 
          FORCE_UNSAFE_CONFIGURE: 1
